services:
  asdf:
    build:
      context: ./asdf/
    image: ohmymndy/asdf:${IMAGE_TAG:?}
    init: true
    volumes:
      - ./asdf/asdf-plugins.sh:/bin/asdf-plugins.sh:ro
    entrypoint: ["/bin/bash", "-c", "tail -f /dev/null"]
    # To test the asdf plugins:
    # docker compose exec asdf /bin/asdf-plugins.sh
