name: "dockerfiles"
services:
  asdf:
    image: ohmymndy/asdf:${IMAGE_TAG:?}
    build:
      context: ./asdf/
    volumes:
      - ./asdf/asdf-plugins.sh:/bin/asdf-plugins.sh:ro
    entrypoint: ["/bin/bash", "-c", "tail -f /dev/null"]
    init: true
