services:
  proxy-all:
    image: ohmymndy/proxy-all:${IMAGE_TAG:?}
    build:
      context: ./proxy-all
      args:
        - IMAGE_TAG=${IMAGE_TAG:?}
    volumes:
      - proxy-all-access-logs:/app/logs
    environment:
      - TARGET_URL=https://api.deezer.com
    ports:
      - "5030:8000"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-q",
          "-T",
          "1",
          "http://0.0.0.0:8000/healthz",
        ]
      interval: 1m
      timeout: 1s
      start_period: 30s
      start_interval: 2s
    user: 65534:1000
    init: true

  proxy-all-access-logs:
    image: docker.elastic.co/beats/filebeat:9.0.1
    depends_on:
      - proxy-all
    volumes:
      - ./proxy-all/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - proxy-all-access-logs:/app/logs
    command: ["filebeat", "-e", "-c", "/usr/share/filebeat/filebeat.yml"]
    restart: unless-stopped

volumes:
  proxy-all-access-logs:
