include:
  - docker-compose.kasm.yml
  - docker-compose.lda.yml
  - docker-compose.proxy-all.yml
  - docker-compose.distrobox.yml

services:
  insync:
    build:
      context: ./insync
      args:
        - IMAGE_TAG=${IMAGE_TAG:?}
    image: ohmymndy/insync:${IMAGE_TAG:?}

  virter:
    build:
      context: ./virter
      args:
        - IMAGE_TAG=${IMAGE_TAG:?}
    privileged: true
    image: ohmymndy/virter:${IMAGE_TAG:?}

volumes:
  proxy-all-access-logs:
