services:
  kasm-ubuntu-base:
    build:
      context: ./kasm/kasm-ubuntu-base
    image: ohmymndy/kasm-ubuntu-base:${IMAGE_TAG:?}
    shm_size: 1gb
    ports:
      - 6902:6901/tcp
      - 6902:6901/udp

#  kasm-obsidian:
#    build:
#      context: ./kasm/kasm-obsidian
#      args:
#        - IMAGE_TAG=${IMAGE_TAG:?}
#    image: ohmymndy/kasm-obsidian:${IMAGE_TAG:?}
#    shm_size: 1gb
#    ports:
#      - 6901:6901/tcp
#      - 6901:6901/udp
#    environment:
#      - VNC_PW=password
#    depends_on:
#      - kasm-ubuntu-base

  kasm-ubuntu-nix-base:
    build:
      context: ./kasm/kasm-ubuntu-nix-base
      args:
        - IMAGE_TAG=${IMAGE_TAG:?}
    image: ohmymndy/kasm-ubuntu-nix-base:${IMAGE_TAG:?}
    shm_size: 1gb
    ports:
      - 6902:6901/tcp
      - 6902:6901/udp
    environment:
      - VNC_PW=password
    depends_on:
      - kasm-ubuntu-base

  kasm-el-base:
    build:
      context: ./kasm/kasm-el-base
    image: ohmymndy/kasm-el-base:${IMAGE_TAG:?}
    shm_size: 1gb

  kasm-el-nix-base:
    build:
      context: ./kasm/kasm-el-nix-base
      args:
        - IMAGE_TAG=${IMAGE_TAG:?}
    image: ohmymndy/kasm-el-nix-base:${IMAGE_TAG:?}
    shm_size: 1gb
    ports:
      - 6903:6901/tcp
      - 6903:6901/udp
    environment:
      - VNC_PW=password
    depends_on:
      - kasm-el-base
