#!/usr/bin/with-contenv ash

# @see https://raw.githubusercontent.com/linuxserver/docker-baseimage-alpine/master/root/etc/cont-init.d/10-adduser


if [[ -n $USER ]] && [[ -n $HOME ]]; then
	PUID="${PUID:-1000}"
	PGID="${PGID:-1000}"
	
	addgroup -g "$PGID" "$USER"
	adduser -u "$PUID" "$USER"

	# chown "$USER:$USER" -R "$HOME"
fi

if [[ -n $DOCKER_GID ]] && [[ -n $USER ]]; then
    addgroup -g "$DOCKER_GID" docker;
    addgroup -g "$DOCKER_GID" docker;
    adduser "$DOCKER_GID" "$USER";
fi
