#!/usr/bin/with-contenv bash
set -e

sudo groupmod -o --gid "$PLUGDEV_GROUP_ID" plugdev
sudo groupmod -o --gid "$INPUT_GROUP_ID" input


# echo 'SUBSYSTEM=="usb", MODE="0660", GROUP="input"' | sudo tee /etc/udev/rules.d/00-usb-permissions.rules
# sudo udevadm control --reload-rules

# sudo chown -R root:input /dev/bus/usb

/opt/retropie/supplementary/emulationstation/scripts/inputconfiguration.sh

s6-setuidgid $USER rsync -hrtp /opt/retropie/configs/all/skyscraper/ "$HOME/.skyscraper"

s6-setuidgid $USER /bin/20-setup-user