Vagrant.require_version ">= 1.6.0"


$script = <<-SCRIPT
sudo apt update
sudo apt install docker.io -y
sudo systemctl start docker
sudo systemctl enable docker

sudo usermod -aG docker vagrant

echo Provisioning done
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: $script
    config.vm.box = "ubuntu/focal64"
end