Vagrant.require_version ">= 1.6.0"


$script = <<-SCRIPT
sudo yum install -y docker
sudo -E tee /etc/docker/daemon.json << EOL &>/dev/null
{
	"log-driver": "json-file",
	"log-opts": {
	    "max-size": "4m",    
	    "max-file": "3"    
    },
	"dns": ["1.1.1.1", "1.0.0.1"],
	"init": true,
	"default-ulimits": {
		"core": {
			"Name": "core",
			"Hard": 0,
			"Soft": 0
		}
	}
} 
EOL
sudo systemctl restart docker
sudo systemctl enable docker

sudo groupadd docker
sudo chown root:docker /var/run/docker.sock
sudo usermod -aG docker vagrant

echo Provisioning done
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: $script
    config.vm.box = "centos/7"
end