name: Build and Push OCI Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    # At 00:00 on Sunday
    - cron: "0 0 * * 0"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - uses: extractions/setup-just@v3

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main' && !env.ACT
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Lint
        run: |
          just lint

      - name: Build images
        env:
          DOCKER_BUILDKIT: 1
        run: |
          IMAGE_TAG="$(cat version.txt)"
          export IMAGE_TAG
          just build

          IMAGE_TAG="latest"
          just build
      - name: Push images
        if: github.ref == 'refs/heads/main' && ! env.ACT
        env:
          DOCKER_BUILDKIT: 1
        run: |
          IMAGE_TAG="$(cat version.txt)"
          export IMAGE_TAG
          just push

          IMAGE_TAG="latest"
          just push
