name: Build and Push OCI Images

on:
  push:
    branches:
      - main
  schedule:
    # At 00:00 on Sunday
    - cron:  "0 0 * * 0"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: extractions/setup-just@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        env:
          DOCKER_BUILDKIT: 1
        run: |
          IMAGE_TAG="$(cat version.txt)"
          export IMAGE_TAG
          just build
          just push

          IMAGE_TAG="latest"
          just build
          just push
