name: Build and Push OCI Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: extractions/setup-just@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        env:
          DOCKER_BUILDKIT: 1
        run: |
          IMAGE_TAG="$(cat version.txt)"
          just build
          just push

          IMAGE_TAG="latest"
          just build
          just push