name: Build and Push OCI Images

on:
  push:
    branches:
      - main

env:
  DOCKER_COMPOSE_FILE: docker-compose.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        env:
          DOCKER_BUILDKIT: 1
        run: |
          IMAGE_TAG="$(cat version.txt)"
          docker compose pull || true
          docker compose build
          docker compose push