name: Build and Push OCI Images

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    # At 00:00 on Sunday
    - cron: "0 0 * * 0"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: extractions/setup-just@v2

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images
        env:
          DOCKER_BUILDKIT: 1
        run: |
          IMAGE_TAG="$(cat version.txt)"
          export IMAGE_TAG
          just build

          IMAGE_TAG="latest"
          just build
      - name: Push images
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_BUILDKIT: 1
        run: |
          IMAGE_TAG="$(cat version.txt)"
          export IMAGE_TAG
          just push

          IMAGE_TAG="latest"
          just push
