#!/usr/bin/with-contenv bash

set -e

rm -f /run/dbus/pid
mkdir -p /var/run/dbus
dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address


while true; do 
    pgrep dbus-daemon &>/dev/null
    sleep 10
done